### ISSUE TITLE
The repository contains binary outputs and intermediate derivatives

### ISSUE THREAD

**Issue by eduard-malakhov** [bprosic/RawReminder#1]
The repository contains binary outputs of the project, i.e. Mischel.Synchronization.dll and log4net.dll (with log4net.xml) as well as intermediate derivatives in obj/* Submitting these files like any other files that can be derived from the source is strongly discouraged. The rule is to store in the repository only those files that developers produce, not anything that can be automatically derived from them. Storing binary files like *.dll and *.obj, in addition, clutters the repository with heavy binary files that git and other SCM systems are not optimized to work with.

**Comment by bprosic** [comment]
Thank you for reporting an issue. Repository contains no more binary outputs of the project.
